# Site settings
title: Continuous Delivery Maturity Model
description: Continuous Delivery Maturity Model
baseurl: ""
url: "https://codemamo.lakruzz.com"
name:  Continuous Delivery Maturity Model # can be overriden by site.client.name
logo:  /images/cards-icon.png             # can be overriden by site.client.logo
frontpage-title: Continuous Delivery Maturity Model

client:
  directory:  lakruzz
  name:       lakruzz
  url:        https://codemamo.lakruzz.com
  logo:       /images/lakruzz/cards-icon.png
name:         Continuous Delivery Maturity Model

# Build settings
remote_theme: thetechcollective/minimal-mistakes
markdown: kramdown
future: true

collections:
  areas:
    output: true
    permalink: /areas/:title/
  levels:
    output: true
    permalink: /levels/:title/
  cards:
    output: true
    permalink: /:title/
  gauges:
    output: true
    permalink: /gauges/:title/
  customer_details:
    output: true

defaults:
  -
    scope:
      type: areas
    values:
      layout: tag
  -
    scope:
      type: levels
    values:
      layout: tag
  -
    scope:
      type: cards
    values:
      layout: card
  -
    scope:
      path: "" # any file
    values:
      layout: page
