# override the settings in _config.yml

title                    : *title
description              : *description
subtitle                 : *subtitle

client:
  directory:  man
  name:       MAN Energy Solutions
#  url:       
#  logo:      
name:         CoDeMeMo Report


