
name: Deploy
# This workflow is triggered by 'ready' branches 

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  call_jekyll_build: 
    name: Build
    permissions:
      statuses: write
      actions: write
    secrets:
      READY_PUSHER: ${{ secrets.READY_PUSHER }}
    uses: thetechcollective/workflows/.github/workflows/jekyll_build.yml@main

  deploy:
    name: Deploy to GitHub Pages
    permissions:
      statuses: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    needs: call_jekyll_build
    steps:
      - name: Install gh dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install thetechcollective/gh-set-status --pin stable 

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4    

        # Always upload for Pages deployment (required by actions/deploy-pages)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: ${{ github.repository}}-${{ github.sha }}

      - name: Deploy to GitHub Pages
        id: deployment
        continue-on-error: true
        uses: actions/deploy-pages@v4
        with:
          artifact-name: ${{ github.repository}}-${{ github.sha }}
        
      - name: Set deployment status
        id: deployed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if : ${{ steps.deployment.outputs.page_url != '' }}
        run: |
          if ${ steps.deployment.outputs.page_url != '' }; then
            echo "Deployment successful: ${{ steps.deployment.outputs.page_url }}"
            gh set-status success "Deployment successful: ${{ steps.deployment.outputs.page_url }}"
            exit 0
          else
            echo "Deployment failed."
            gh set-status failure "Deployment failed"
            exit 1
          fi

