
name: Ready
# This workflow is triggered by 'ready' branches 

on:
  workflow_dispatch:
  push:
    branches: 
      - 'ready/*'
      
jobs:

  call_jekyll_build: 
    name: Build
    permissions:
      statuses: write
      actions: write
    secrets:
      READY_PUSHER: ${{ secrets.READY_PUSHER }}
    uses: thetechcollective/workflows/.github/workflows/jekyll_build.yml@main

  call_cspell_check:
    name: Spell check
    permissions:
      statuses: write
    uses: thetechcollective/workflows/.github/workflows/cspell_check.yml@main

  call_markdown_linter_check:
    name: Linting
    permissions:
      statuses: write
    uses: thetechcollective/workflows/.github/workflows/markdown_linter.yml@main
  
  merge:
    needs: 
      - call_cspell_check
      - call_markdown_linter_check
      - call_jekyll_build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.READY_PUSHER }}
        # This token is used to commit the changes back to the main branch

    - name: Set up git config
      run: |
        git config --global user.name "GitHub Action: ready"
        git config --global user.email "ready-pusher@lakruzz.com"

    - name: Fast-Forward merge back to main
      env:
        GITHUB_TOKEN: ${{ secrets.READY_PUSHER }}

        # checkout the main branch, fast-forward merge the changes from the ready branch and push the changes to origin
      run: |
        git checkout main
        git merge --ff-only ${{ github.sha }}
        git push origin main
        echo "Successfully fast-forward merged '${{ github.sha }}' into main"  >> $GITHUB_STEP_SUMMARY

  close_issue:
    needs: merge
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:

    - uses: actions/checkout@v4

    - name: Set up git config
      run: |
        git config --global user.name "GitHub Action: ready"
        git config --global user.email "ready-pusher@lakruzz.com"

    - name: Close the issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # checkout the main branch, fast-forward merge the changes from the ready branch and push the changes to origin
      run: |
        # Read the github.ref_name to get the branch name
        # The branch name is in the format 'ready/123.*'
        # get the number from the branch name after 'ready/'
        ISSUE_NUMBER=$(echo "${{ github.ref_name }}" | grep -oP '(?<=ready/)\d+')

        gh issue close "$ISSUE_NUMBER" --repo "${{ github.repository }}" --comment "Merged into main branch with commit ${{ github.sha }}"  >> $GITHUB_STEP_SUMMARY

        git push origin ":${{ github.ref_name }}"
        echo "Deleted branch '${{ github.ref_name }}' from remote"  >> $GITHUB_STEP_SUMMARY

        ISSUE_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/ready\///')
        git push origin ":${ISSUE_BRANCH}"
        echo "Deleted branch '${ISSUE_BRANCH}' from remote"  >> $GITHUB_STEP_SUMMARY

