name: Wrapup
# This workflow is triggered on push to branches that begins with a number (issue-branches)
# It's designed to support the wrapup process in thetechcollective/gh-tt GitHub CLI extension
on:
  workflow_dispatch:
  push:
    branches: 
      - '[0-9]*'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
        
  cspell_check:
    name: Spelling
    permissions:
      statuses: write
    uses: lakruzz/workflows/.github/workflows/cspell_check.yml@experimental
    with:
      config_file: cspell.json 

  markdown_linter:
    name: Linting
    permissions:
      statuses: write
    uses: lakruzz/workflows/.github/workflows/markdown_linter.yml@experimental
    with:
      config_file: .markdownlint.json
